services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/var/www/html
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-gue55me}@database:5432/${POSTGRES_DB:-app}?serverVersion=${POSTGRES_VERSION:-16}
      JWT_PRIVATE_KEY: "${JWT_PRIVATE_KEY}"
      JWT_PUBLIC_KEY: "${JWT_PUBLIC_KEY}"
      JWT_PASSPHRASE: "${JWT_PASSPHRASE}"
      OAUTH_GOOGLE_CLIENT_ID: "${OAUTH_GOOGLE_CLIENT_ID}"
      OAUTH_GOOGLE_CLIENT_SECRET: "${OAUTH_GOOGLE_CLIENT_SECRET}"
      FRONTEND_URL: "http://localhost:5173"
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      AWS_REGION: us-east-1
      AWS_BUCKET: app
      AWS_ENDPOINT: http://objectstore:9000
      MESSENGER_TRANSPORT_DSN: redis://queue:6379/messages
    ports:
      - "9000:9000"
    restart: always
    depends_on:
      - database
      - queue
      - objectstore

  worker:
    build:
      context: ./api
      dockerfile: Dockerfile.worker
    volumes:
      - ./api:/var/www/html
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-gue55me}@database:5432/${POSTGRES_DB:-app}?serverVersion=${POSTGRES_VERSION:-16}
      GEMINI_API_KEY: "${GEMINI_API_KEY}"
      MESSENGER_TRANSPORT_DSN: redis://queue:6379/messages
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      AWS_REGION: us-east-1
      AWS_BUCKET: app
      AWS_ENDPOINT: http://objectstore:9000
    restart: always
    depends_on:
      - database
      - queue
      - objectstore


  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      NGINX_FASTCGI_PASS: "api:9000"
      FRONTEND_ORIGIN: "http://localhost:5173"
    command: ["/bin/sh", "-c", "/start.sh"]
    depends_on:
      - api
      - web

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-gue55me}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  queue:
    image: redis:alpine
    ports:
      - "6379:6379"

  objectstore:
    image: minio/minio
    ports:
      - "10001:10001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKETS: app
    command: server /data --console-address ":10001"

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      VITE_API_URL: http://localhost:8080
    depends_on:
      - api

volumes:
  database_data:
  minio_data:
